#!/usr/bin/env bash

#
# Copyright 2007-2019 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compatible shell to run this script. If your /bin/sh is
#       Windows or otherwise incompatible, but you have some other POSIX shell
#       installed, then you can use it, e.g., ksh.
#
#   (2) This script expects to be called with gradlew which is a symlink
#       to the script. It is not run directly.
#
#   (3) This script is generated from the Groovy template
#       gradle/wrapper/gradlew.template by the Gradle build.
#
#       You can find Gradle at https://gradle.org/
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"/${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( command -p ls -ld "$app_path" )
    link=${ls#*' -> '}
    app_path=$link
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd )

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
        echo "Please set the JAVA_HOME variable in your environment to match the"
        echo "location of your Java installation."
        exit 1
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || { echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."; exit 1; }
fi

# Increase the default file descriptors limit, fix issues on macOS and
# refuse to run when it cannot be increased.
MAX_FD="maximum"

if [ "$os" = "Darwin" ] ; then
    if [ -z "$GRADLE_OPTS" ] ; then
        GRADLE_OPTS="-Xmx512m"
    fi
else
    if [ -z "$GRADLE_OPTS" ] ; then
        GRADLE_OPTS="-Xmx512m"
    fi
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * java system properties
#   * application properties
#   * main class name

# Add standard JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options here.
DEFAULT_JVM_OPTS='"-Xmx512m"'

# Use the appropriate separator based on the operating system.
# This is used to handle paths with spaces correctly.
if [ -z "$GRADLE_OPTS" ] ; then
    GRADLE_OPTS=""
fi

# Determine how the application should be called.
MAIN_CLASS_NAME="org.gradle.wrapper.GradleWrapperMain"

# Collect all arguments for the java command.
#   * args from the command line
#   * the main class name
#   * -classpath
#   * java system properties
#   * application properties

# Now launch the app.
exec "$JAVACMD" \
    $DEFAULT_JVM_OPTS \
    -classpath "$CLASSPATH" \
    "$MAIN_CLASS_NAME" \
    "$@"
