name: Build APK
on: [push]

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version=8.5
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build APK
        run: ./gradlew clean assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: EZBox-debug
          path: app/build/outputs/apk/debug/EZBox-debug.apk

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/debug/EZBox-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
